import React from "react";
import Layout from "../components/Layout";

const CookiePolicy = () => {
  return (
    <Layout>
      <main className="container mx-auto py-10 px-6 md:px-20 lg:px-40 prose prose-sm sm:prose lg:prose-lg max-w-none">
        <h1 className="text-primary text-4xl font-bold my-8">Cookie Policy</h1>

        <p>
          <strong>Effective Date:</strong> 15-Apr-2025 <br />
          <strong>Last Updated:</strong> 15-Apr-2025
        </p>

        <h5>What are cookies?</h5>
        <p>
          This Cookie Policy explains what cookies are and how we use them, the types of cookies we use (i.e., the information we collect using cookies and how that information is used), and how to manage your cookie settings.
        </p>
        <p>
          Cookies are small text files that are used to store small pieces of information. They are stored on your device when the website is loaded on your browser. These cookies help us make the website function properly, make it more secure, provide a better user experience, and analyze what works and what needs improvement.
        </p>

        <h5>How do we use cookies?</h5>
        <p>
          As with most online services, our website uses first-party and third-party cookies for various purposes. First-party cookies are primarily necessary for the website to function properly and do not collect your personally identifiable data.
        </p>
        <p>
          Third-party cookies help us understand how the website performs, how you interact with it, keep our services secure, provide relevant advertisements, and offer an improved user experience.
        </p>

        <h5>Types of Cookies we use</h5>
        <div className="cky-audit-table-element" />

        <h5>Manage cookie preferences</h5>
        <p>
          You can change your cookie preferences any time by clicking the button below. This will reopen the cookie banner where you can update your consent.
        </p>
        <a className="cky-banner-element">Cookie Settings</a>

        <p>Browser-specific instructions for managing cookies:</p>
        <ul>
          <li>Chrome: <a href="https://support.google.com/accounts/answer/32050" target="_blank" rel="noopener noreferrer">Manage cookies in Chrome</a></li>
          <li>Safari: <a href="https://support.apple.com/en-in/guide/safari/sfri11471/mac" target="_blank" rel="noopener noreferrer">Manage cookies in Safari</a></li>
          <li>Firefox: <a href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox" target="_blank" rel="noopener noreferrer">Manage cookies in Firefox</a></li>
          <li>Internet Explorer: <a href="https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc" target="_blank" rel="noopener noreferrer">Delete cookies in IE</a></li>
        </ul>

        <p className="cookie-policy-p">
          Cookie Policy generated by <a href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW" target="_blank" rel="noopener noreferrer">CookieYes</a>.
        </p>
      </main>
    </Layout>
  );
};

export default CookiePolicy;

export const Head = () => {
  const siteUrl = "https://zencarbuying.com";
  const pageUrl = `${siteUrl}/cookie-policy`;

  return (
    <>
      <title>Cookie Policy | Zen Car Buying</title>
      <meta name="description" content="Learn how Zen Car Buying uses cookies to enhance your experience and manage your data securely." />
      <link rel="canonical" href={pageUrl} />
      <meta property="og:title" content="Cookie Policy | Zen Car Buying" />
      <meta property="og:description" content="Learn how Zen Car Buying uses cookies to enhance your experience and manage your data securely." />
      <meta property="og:url" content={pageUrl} />
      <meta property="og:type" content="website" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Cookie Policy | Zen Car Buying" />
      <meta name="twitter:description" content="Learn how Zen Car Buying uses cookies to enhance your experience and manage your data securely." />
      <script type="application/ld+json">
        {JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebPage",
          url: pageUrl,
          name: "Cookie Policy",
          description: "Learn how Zen Car Buying uses cookies to enhance your experience and manage your data securely."
        })}
      </script>
    </>
  );
};
